product-name = "src-tauri"
version = "0.0.0"
identifier = "com.tauri.dev"

[build]
dev-url = "http://localhost:1420"
before-dev-command = { cwd = "../src-ui", script = "trunk serve" }
before-build-command = { cwd = "../src-ui", script = "trunk build" }
frontend-dist = "../src-ui/dist"

[bundle]
active = true
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]

[app]
with-global-tauri = true

[[app.windows]]
title = "MyApp"
width = 800
height = 600
# decorations = false
